--- 
title: "Sequencing databases in Shiny"
author: "AMB and NZ"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  Here we will describe how to build a Shiny app for sequencing data using the code base described in Zhao et al.
link-citations: yes
github-repo: "aliibarry/omics-database"
site: bookdown::bookdown_site
---

# Overview

Here we will describe how to build a Shiny app for sequencing data using the code base described in _Predicting “pain genes”: multi-modal data integration using probabilistic classifiers and interaction networks_ *(Zhao et al., in review)*.

A working example of this app is hosted at <https://livedataoxford.shinyapps.io/drg-directory/> and the code base is provided at <https://github.com/aliibarry/omics-database>.

A previous version of <https://livedataoxford.shinyapps.io/drg-directory/> was first published in Barry _et al._ 2023 but was updated here to reflect a more developer-friendly code base along with addition features (eg. network integration). 

## Shiny

If you are completely new to Shiny, we recommend working through some short tutorials first, just to wrap your head around the structure <https://shiny.rstudio.com/tutorial/written-tutorial/lesson1/>.

## Workflow
1. Data processing (\@ref(data))
* Prepare tables (count, differential analysis, column data)
* Compile into a `.RData` or `.db`
2. User interface (\@ref(ui))
* Write descriptions for each dataset and save them in `.\des\*`
* _encouraged_ select appropriate plots and add descriptions
* _encouraged_ choose title + logo
* _optional_ customize aesthetic
3. Server (\@ref(server))
* Create a description dataframe `des_df` for the datasets included
* Specify directory storing your data
* _optional_ customize figure aesthetic by modifying provided functions
* _optional_ build your own functions (and link to the UI)
4. Deploy (\@ref(deploy))
* Deploy your app using `rsconnect::deployApp()`

Happy building!
  

---


This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.


<!-- Each **bookdown** chapter is an .Rmd file, and each .Rmd file can contain one (and only one) chapter. A chapter *must* start with a first-level heading: `# A good chapter`, and can contain one (and only one) first-level heading. -->

<!-- Use second-level and higher headings within chapters like: `## A short section` or `### An even shorter section`. -->

<!-- The `index.Rmd` file is required, and is also your first book chapter. It will be the homepage when you render the book. -->

<!-- ## Render book -->

<!-- You can render the HTML version of this example book without changing anything: -->

<!-- 1. Find the **Build** pane in the RStudio IDE, and -->

<!-- 1. Click on **Build Book**, then select your output format, or select "All formats" if you'd like to use multiple formats from the same book source files. -->

<!-- Or build the book from the R console: -->

<!-- ```{r, eval=FALSE} -->
<!-- bookdown::render_book() -->
<!-- ``` -->

<!-- To render this example to PDF as a `bookdown::pdf_book`, you'll need to install XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>. -->

<!-- ## Preview book -->

<!-- As you work, you may start a local server to live preview this HTML book. This preview will update as you edit the book when you save individual .Rmd files. You can start the server in a work session by using the RStudio add-in "Preview book", or from the R console: -->

<!-- ```{r eval=FALSE} -->
<!-- bookdown::serve_book() -->
<!-- ``` -->


<!-- ```{r include=FALSE} -->
<!-- # automatically create a bib database for R packages -->
<!-- knitr::write_bib(c( -->
<!--   .packages(), 'bookdown', 'knitr', 'rmarkdown' -->
<!-- ), 'packages.bib') -->
<!-- ``` -->
